/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.RoomController;

/**
 *
 * @author ViktorKim
 */
public class DifficultySelector extends javax.swing.JFrame {


    public DifficultySelector() 
    {
        initComponents();
        this.setVisible(true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEventyr = new javax.swing.JLabel();
        jLabelSize = new javax.swing.JLabel();
        jLabelWidth = new javax.swing.JLabel();
        jSliderX = new javax.swing.JSlider();
        jLabelHeigth = new javax.swing.JLabel();
        jSliderY = new javax.swing.JSlider();
        jButtonGenerate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dungeon Size Selector");

        jLabelEventyr.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelEventyr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEventyr.setText("Eventyr Simulator 2017");

        jLabelSize.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSize.setText("Select Dungeon Size:");

        jLabelWidth.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelWidth.setText("Dungeon Width:");

        jSliderX.setMaximum(9);
        jSliderX.setMinimum(2);
        jSliderX.setMinorTickSpacing(1);
        jSliderX.setPaintLabels(true);
        jSliderX.setPaintTicks(true);
        jSliderX.setSnapToTicks(true);
        jSliderX.setValue(5);

        jLabelHeigth.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelHeigth.setText("Dungeon Heigth:");

        jSliderY.setMaximum(9);
        jSliderY.setMinimum(2);
        jSliderY.setMinorTickSpacing(1);
        jSliderY.setPaintLabels(true);
        jSliderY.setPaintTicks(true);
        jSliderY.setSnapToTicks(true);
        jSliderY.setToolTipText("");
        jSliderY.setValue(5);

        jButtonGenerate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonGenerate.setText("GENERATE DUNGEON");
        jButtonGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEventyr, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSize, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jSliderX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelHeigth)
                                .addGap(25, 25, 25)
                                .addComponent(jSliderY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButtonGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEventyr)
                .addGap(11, 11, 11)
                .addComponent(jLabelSize)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelWidth))
                    .addComponent(jSliderX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabelHeigth)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)))
                .addComponent(jButtonGenerate)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateActionPerformed
        int x = jSliderX.getValue();
        int y = jSliderY.getValue();
        new MainWindow(new RoomController(x, y));
        this.dispose();
    }//GEN-LAST:event_jButtonGenerateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerate;
    private javax.swing.JLabel jLabelEventyr;
    private javax.swing.JLabel jLabelHeigth;
    private javax.swing.JLabel jLabelSize;
    private javax.swing.JLabel jLabelWidth;
    private javax.swing.JSlider jSliderX;
    private javax.swing.JSlider jSliderY;
    // End of variables declaration//GEN-END:variables
}
